/**
 * Submodules import
 *
 */
dependencies {
   implementation project(":task-tracker-api-miscellaneous:store")
}

/**
 * Spring
 */
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-json'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
}

/**
 * Mapstruct
 */
dependencies {
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    testAnnotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
}

/**
 * Other
 */
dependencies {
    runtimeOnly 'org.postgresql:postgresql'
}
