spring:
  application:
    name: task-tracker-api
  datasource:
    url: jdbc:postgresql://localhost:5432/task-tracker
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

