spring:
  application:
    name: task-tracker-api
  datasource:
    url: jdbc:postgresql://localhost:5432/task-tracker
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: # Цей рівень має бути вкладеним під properties
        show_sql: true # Використовуйте show_sql, не show-sql для властивостей Hibernate
        format_sql: true
server:
  port: 8080

